server:
  port: 8002

spring:
  security:
    oauth2:
      client:
        registration:
          app-b:
            provider: sso
            client-id: app-b
            client-secret: app-b
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8002/login/oauth2/code/app-b
            scope: openid
            client-name: App-B
        provider:
          sso:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

logging:
  level:
    root: DEBUG