server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          app-a:
            registration:
              client-id: "app-a"
              client-secret: "{noop}app-a"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8001/login/oauth2/code/app-a"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8001/authorized"
              scopes:
                - "openid"
          app-b:
            registration:
              client-id: "app-b"
              client-secret: "{noop}app-b"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8002/login/oauth2/code/app-b"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8002/authorized"
              scopes:
                - "openid"

logging:
  level:
    root: DEBUG